backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/img"
public_folder: "img"
collections:
  - name: "publication" # Used in routes, e.g., /admin/collections/blog
    label: "Publication" # Used in the UI
    folder: "content/publication" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Authors", name: "authors", widget: "list", default: ["Gruber Sylvia"]}
      - label: "Type"
        name: "publication_types"
        widget: "list"
        default: ["2"]
        field:
          - label: pType
            name: pType
            widget: select
            options:
              - { label: "Uncategorized", value: "0" }
              - { label: "Conference Proceedings", value: "1" }
              - { label: "Journal", value: "2" }
              - { label: "Work in Progress", value: "3" }
              - { label: "Technical Report", value: "4" }
              - { label: "Book", value: "5" }
              - { label: "Book Chapter", value: "6" }
      - {label: "Publication", name: "publication", widget: "string", default: "In *International Journal of Things*"}
      - {label: "Abstract", name: "abstract", widget: "text"}
      - {label: "Selected Publication?", name: "selected", widget: "boolean"}
      - {label: "Includes Math?", name: "selected", widget: "boolean"}
      - {label: "Code Highlighting?", name: "selected", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
      #TODO: Include links to projects?
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home/about.md"
        label: "Home Page"
        name: "about"
        fields:
          - {label: "Widget", name: "widget", widget: "hidden", default: "about"}
          - {label: "Active", name: "active", widget: "hidden", default: "true"}
          - {label: "Body", name: "body", widget: "markdown"}
